CREATE TABLE IF NOT EXISTS Users (id SERIAL PRIMARY KEY, name TEXT, password TEXT);
CREATE TABLE IF NOT EXISTS Chats (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS Messages (id SERIAL PRIMARY KEY, time TIMESTAMP, chat_id INTEGER REFERENCES Chats ON DELETE CASCADE, user_id INTEGER REFERENCES Users ON DELETE SET NULL, content TEXT);
CREATE TABLE IF NOT EXISTS ChatMembers (chat_id INTEGER REFERENCES Chats ON DELETE CASCADE, user_id INTEGER REFERENCES Users ON DELETE CASCADE, present BOOLEAN);
CREATE TABLE IF NOT EXISTS ChatGroups (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES Users, name TEXT, index INTEGER);
CREATE TABLE IF NOT EXISTS ChatGroupChats (chat_group_id INTEGER REFERENCES ChatGroups ON DELETE CASCADE, chat_id INTEGER REFERENCES Chats ON DELETE CASCADE);