CREATE TABLE IF NOT EXISTS Users (id SERIAL PRIMARY KEY, name TEXT, password TEXT);
CREATE TABLE IF NOT EXISTS Chats (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS Messages (id SERIAL PRIMARY KEY, time TIMESTAMP, user_id INTEGER REFERENCES Users ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS ChatMembers (chat_id INTEGER REFERENCES Chats ON DELETE CASCADE, user_id INTEGER REFERENCES Users ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS VisibleChats (chat_id INTEGER REFERENCES Chats ON DELETE CASCADE, user_id INTEGER REFERENCES Users ON DELETE CASCADE);